/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ThemePalette } from '../types';

export interface ThemeConfig {
  id: ThemePalette;
  name: string;
  category: 'light' | 'dark';
  desc: string;
  colors: string[];
  appBg: string;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarText: string;
  sidebarActiveNav: string;
  sidebarHover: string;
  headerBg: string;
  headerBorder: string;
  headerText: string;
  cardBg: string;
  cardBorder: string;
  cardTitle: string;
  cardSubtext: string;
  inputBg: string;
  inputBorder: string;
  inputText: string;
  accentBtn: string;
  accentBtnText: string;
  badgeBg: string;
  badgeText: string;
  textPrimary?: string;
  textSecondary?: string;
  textMuted?: string;
  surfaceBg?: string;
  borderSubtle?: string;
  containerBg?: string;
  cardBgHover?: string;
  buttonSecondaryBg?: string;
}

export const THEME_CONFIGS: Record<ThemePalette, ThemeConfig> = {
  classic: {
    id: 'classic',
    name: 'Архівний Класик',
    category: 'light',
    desc: 'Теплий білий фон із золотисто-вохристими акцентами',
    colors: ['#F9F8F6', '#FFFFFF', '#B88E3E', '#1F1E1D'],
    appBg: 'bg-[#F9F8F6] text-neutral-900',
    sidebarBg: 'bg-[#1F1E1D] text-neutral-200',
    sidebarBorder: 'border-[#33312E]',
    sidebarText: 'text-neutral-300',
    sidebarActiveNav: 'bg-[#B88E3E] text-white font-medium',
    sidebarHover: 'hover:bg-neutral-800 hover:text-white',
    headerBg: 'bg-white text-neutral-900',
    headerBorder: 'border-neutral-200/80',
    headerText: 'text-neutral-900',
    cardBg: 'bg-white',
    cardBorder: 'border-neutral-200',
    cardTitle: 'text-neutral-900',
    cardSubtext: 'text-neutral-600',
    inputBg: 'bg-white',
    inputBorder: 'border-neutral-300',
    inputText: 'text-neutral-900',
    accentBtn: 'bg-[#B88E3E] hover:bg-[#A37B30]',
    accentBtnText: 'text-white',
    badgeBg: 'bg-[#B88E3E]/10',
    badgeText: 'text-[#8E6C28]',
  },
  'light-parchment': {
    id: 'light-parchment',
    name: 'Світлий Пергамент',
    category: 'light',
    desc: 'М\'який вінтажний папір, спокійні теплі відтінки літопису',
    colors: ['#FAF8F2', '#FFFFFF', '#B88E3E', '#2C271E'],
    appBg: 'bg-[#FAF8F2] text-[#2C271E]',
    sidebarBg: 'bg-[#EFECE1] text-[#4A4234]',
    sidebarBorder: 'border-[#DFD9C7]',
    sidebarText: 'text-[#615847]',
    sidebarActiveNav: 'bg-[#B88E3E] text-white font-medium',
    sidebarHover: 'hover:bg-[#E4DFD0] hover:text-[#2C271E]',
    headerBg: 'bg-[#F4F1E8] text-[#2C271E]',
    headerBorder: 'border-[#DFD9C7]',
    headerText: 'text-[#2C271E]',
    cardBg: 'bg-[#FFFFFF]',
    cardBorder: 'border-[#DFD9C7]',
    cardTitle: 'text-[#2C271E]',
    cardSubtext: 'text-[#7D735E]',
    inputBg: 'bg-[#FFFFFF]',
    inputBorder: 'border-[#DFD9C7]',
    inputText: 'text-[#2C271E]',
    accentBtn: 'bg-[#B88E3E] hover:bg-[#A07A30]',
    accentBtnText: 'text-white',
    badgeBg: 'bg-[#B88E3E]/15',
    badgeText: 'text-[#8E6C28]',
  },
  sepia: {
    id: 'sepia',
    name: 'Старовинна Сепія',
    category: 'light',
    desc: 'Вінтажний архівний тон старовинних метричних книг',
    colors: ['#F7F2E8', '#FCFAF5', '#8C6D4F', '#3D3226'],
    appBg: 'bg-[#F7F2E8] text-[#3D3226]',
    sidebarBg: 'bg-[#2D241E] text-[#E0D5C7]',
    sidebarBorder: 'border-[#453A31]',
    sidebarText: 'text-[#C5B7A5]',
    sidebarActiveNav: 'bg-[#8C6D4F] text-white font-medium',
    sidebarHover: 'hover:bg-[#3E322A] hover:text-white',
    headerBg: 'bg-[#FAF6EF] text-[#3D3226]',
    headerBorder: 'border-[#E3D7C5]',
    headerText: 'text-[#3D3226]',
    cardBg: 'bg-[#FCFAF5]',
    cardBorder: 'border-[#E5DAC8]',
    cardTitle: 'text-[#3D3226]',
    cardSubtext: 'text-[#706050]',
    inputBg: 'bg-[#FAF6EF]',
    inputBorder: 'border-[#D5C6B1]',
    inputText: 'text-[#3D3226]',
    accentBtn: 'bg-[#8C6D4F] hover:bg-[#785C40]',
    accentBtnText: 'text-white',
    badgeBg: 'bg-[#8C6D4F]/15',
    badgeText: 'text-[#614931]',
  },
  amber: {
    id: 'amber',
    name: 'Бурштинова Палітра',
    category: 'light',
    desc: 'Затишний медово-бурштиновий теплий відтінок',
    colors: ['#FCF9F2', '#FFFFFF', '#D97706', '#291E13'],
    appBg: 'bg-[#FCF9F2] text-amber-950',
    sidebarBg: 'bg-[#291E13] text-amber-100',
    sidebarBorder: 'border-[#423221]',
    sidebarText: 'text-amber-300',
    sidebarActiveNav: 'bg-amber-600 text-white font-medium',
    sidebarHover: 'hover:bg-[#3D2C1B] hover:text-white',
    headerBg: 'bg-white text-amber-950',
    headerBorder: 'border-amber-200',
    headerText: 'text-amber-950',
    cardBg: 'bg-white',
    cardBorder: 'border-amber-200',
    cardTitle: 'text-amber-950',
    cardSubtext: 'text-amber-800',
    inputBg: 'bg-white',
    inputBorder: 'border-amber-300',
    inputText: 'text-amber-950',
    accentBtn: 'bg-amber-600 hover:bg-amber-700',
    accentBtnText: 'text-white',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-900',
  },
  emerald: {
    id: 'emerald',
    name: 'Смарагдовий Літопис',
    category: 'light',
    desc: 'Свіжий світлий трав\'янисто-смарагдовий стиль',
    colors: ['#F4F8F6', '#FFFFFF', '#059669', '#0E241B'],
    appBg: 'bg-[#F4F8F6] text-emerald-950',
    sidebarBg: 'bg-[#0E241B] text-emerald-100',
    sidebarBorder: 'border-emerald-900',
    sidebarText: 'text-emerald-300',
    sidebarActiveNav: 'bg-emerald-600 text-white font-medium',
    sidebarHover: 'hover:bg-emerald-900 hover:text-white',
    headerBg: 'bg-white text-emerald-950',
    headerBorder: 'border-emerald-200',
    headerText: 'text-emerald-950',
    cardBg: 'bg-white',
    cardBorder: 'border-emerald-200',
    cardTitle: 'text-emerald-950',
    cardSubtext: 'text-emerald-700',
    inputBg: 'bg-white',
    inputBorder: 'border-emerald-300',
    inputText: 'text-emerald-950',
    accentBtn: 'bg-emerald-700 hover:bg-emerald-800',
    accentBtnText: 'text-white',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
  },
  slate: {
    id: 'slate',
    name: 'Графітовий Слейт',
    category: 'light',
    desc: 'Сучасний контрастний світлий мінімалізм',
    colors: ['#F8FAFC', '#FFFFFF', '#0284C7', '#0F172A'],
    appBg: 'bg-[#F8FAFC] text-slate-900',
    sidebarBg: 'bg-[#0F172A] text-slate-200',
    sidebarBorder: 'border-slate-800',
    sidebarText: 'text-slate-400',
    sidebarActiveNav: 'bg-sky-600 text-white font-medium',
    sidebarHover: 'hover:bg-slate-800 hover:text-white',
    headerBg: 'bg-white text-slate-900',
    headerBorder: 'border-slate-200',
    headerText: 'text-slate-900',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardTitle: 'text-slate-900',
    cardSubtext: 'text-slate-600',
    inputBg: 'bg-white',
    inputBorder: 'border-slate-300',
    inputText: 'text-slate-900',
    accentBtn: 'bg-sky-600 hover:bg-sky-700',
    accentBtnText: 'text-white',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-800',
  },
  nordic: {
    id: 'nordic',
    name: 'Нордичний Синій',
    category: 'light',
    desc: 'Спокійний прохолодний синьо-сірий відтінок',
    colors: ['#F3F6FA', '#FFFFFF', '#4F46E5', '#1E293B'],
    appBg: 'bg-[#F3F6FA] text-[#1E293B]',
    sidebarBg: 'bg-[#182334] text-[#CBD5E1]',
    sidebarBorder: 'border-[#26364D]',
    sidebarText: 'text-[#94A3B8]',
    sidebarActiveNav: 'bg-indigo-600 text-white font-medium',
    sidebarHover: 'hover:bg-[#202E44] hover:text-white',
    headerBg: 'bg-white text-[#1E293B]',
    headerBorder: 'border-[#E2E8F0]',
    headerText: 'text-[#1E293B]',
    cardBg: 'bg-white',
    cardBorder: 'border-[#E2E8F0]',
    cardTitle: 'text-[#1E293B]',
    cardSubtext: 'text-[#64748B]',
    inputBg: 'bg-white',
    inputBorder: 'border-[#CBD5E1]',
    inputText: 'text-[#1E293B]',
    accentBtn: 'bg-indigo-600 hover:bg-indigo-700',
    accentBtnText: 'text-white',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-800',
  },
  royal: {
    id: 'royal',
    name: 'Шляхетний Пурпур',
    category: 'light',
    desc: 'Аристократичний пурпуровий відтінок архіву',
    colors: ['#FAF6FD', '#FFFFFF', '#7E22CE', '#2E1065'],
    appBg: 'bg-[#FAF6FD] text-[#2E1065]',
    sidebarBg: 'bg-[#1E0B38] text-[#E9D5FF]',
    sidebarBorder: 'border-[#3B176B]',
    sidebarText: 'text-[#C084FC]',
    sidebarActiveNav: 'bg-purple-700 text-white font-medium',
    sidebarHover: 'hover:bg-[#2E1156] hover:text-white',
    headerBg: 'bg-white text-[#2E1065]',
    headerBorder: 'border-purple-200',
    headerText: 'text-[#2E1065]',
    cardBg: 'bg-white',
    cardBorder: 'border-purple-200',
    cardTitle: 'text-[#2E1065]',
    cardSubtext: 'text-purple-700',
    inputBg: 'bg-white',
    inputBorder: 'border-purple-300',
    inputText: 'text-[#2E1065]',
    accentBtn: 'bg-purple-700 hover:bg-purple-800',
    accentBtnText: 'text-white',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-900',
  },
  dark: {
    id: 'dark',
    name: 'Нічний Архів',
    category: 'dark',
    desc: 'Глибокий темний графіт для комфортної нічної роботи',
    colors: ['#121214', '#1E1E24', '#D97706', '#F4F4F5'],
    appBg: 'bg-[#121214] text-neutral-100',
    sidebarBg: 'bg-[#18181B] text-neutral-300',
    sidebarBorder: 'border-neutral-800',
    sidebarText: 'text-neutral-400',
    sidebarActiveNav: 'bg-amber-600 text-white font-medium',
    sidebarHover: 'hover:bg-neutral-800 hover:text-white',
    headerBg: 'bg-[#18181B] text-neutral-100',
    headerBorder: 'border-neutral-800',
    headerText: 'text-neutral-100',
    cardBg: 'bg-[#1E1E24]',
    cardBorder: 'border-neutral-800',
    cardTitle: 'text-neutral-100',
    cardSubtext: 'text-neutral-400',
    inputBg: 'bg-[#141416]',
    inputBorder: 'border-neutral-700',
    inputText: 'text-neutral-100',
    accentBtn: 'bg-amber-600 hover:bg-amber-700',
    accentBtnText: 'text-white',
    badgeBg: 'bg-amber-500/15',
    badgeText: 'text-amber-300',
  },
  'dark-emerald': {
    id: 'dark-emerald',
    name: 'Темний Смарагд',
    category: 'dark',
    desc: 'Глибока смарагдова ніч літописного роду',
    colors: ['#061A14', '#09251D', '#10B981', '#E0F2E9'],
    appBg: 'bg-[#061A14] text-[#E0F2E9]',
    sidebarBg: 'bg-[#04120E] text-[#A7D7C5]',
    sidebarBorder: 'border-[#0B3327]',
    sidebarText: 'text-[#85BFA9]',
    sidebarActiveNav: 'bg-[#10B981] text-white font-medium',
    sidebarHover: 'hover:bg-[#0B3327] hover:text-white',
    headerBg: 'bg-[#081F18] text-[#E0F2E9]',
    headerBorder: 'border-[#0F4233]',
    headerText: 'text-[#E0F2E9]',
    cardBg: 'bg-[#09251D]',
    cardBorder: 'border-[#134E3E]',
    cardTitle: 'text-[#E0F2E9]',
    cardSubtext: 'text-[#85BFA9]',
    inputBg: 'bg-[#061A14]',
    inputBorder: 'border-[#134E3E]',
    inputText: 'text-[#E0F2E9]',
    accentBtn: 'bg-[#10B981] hover:bg-[#059669]',
    accentBtnText: 'text-white',
    badgeBg: 'bg-[#10B981]/20',
    badgeText: 'text-[#34D399]',
  },
};

export function getThemeConfig(palette?: ThemePalette): ThemeConfig {
  const base = (palette && THEME_CONFIGS[palette]) ? THEME_CONFIGS[palette] : THEME_CONFIGS.classic;
  const isDark = base.category === 'dark';

  return {
    ...base,
    textPrimary: base.textPrimary || base.cardTitle || (isDark ? 'text-neutral-100' : 'text-neutral-900'),
    textSecondary: base.textSecondary || base.cardSubtext || (isDark ? 'text-neutral-300' : 'text-neutral-700'),
    textMuted: base.textMuted || (isDark ? 'text-neutral-400' : 'text-neutral-500'),
    surfaceBg: base.surfaceBg || (isDark ? 'bg-black/30' : 'bg-neutral-100/60'),
    borderSubtle: base.borderSubtle || base.cardBorder || (isDark ? 'border-neutral-800' : 'border-neutral-200'),
    containerBg: base.containerBg || base.appBg.split(' ')[0] || (isDark ? 'bg-neutral-950' : 'bg-neutral-50'),
    cardBgHover: base.cardBgHover || (isDark ? 'hover:bg-neutral-800/80' : 'hover:bg-neutral-100/80'),
    buttonSecondaryBg: base.buttonSecondaryBg || (isDark ? 'bg-neutral-800' : 'bg-neutral-100'),
  };
}
